apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: observability
data:
  promtail.yaml: |   # ðŸ”¹ Ajustei o nome para ficar igual ao subPath no DaemonSet
    server:
      http_listen_port: 9080

    positions:
      filename: /var/log/positions.yaml

    clients:
      - url: "http://loki:3100/loki/api/v1/push"

    scrape_configs:
      - job_name: "varlogs"
        static_configs:
          - targets:
              - localhost
            labels:
              job: "varlogs"
              __path__: /var/log/*.log"


